from __future__ import annotations

from django.urls import path
from django.views.generic import RedirectView

from vulnhunter.web import (
    active_validation_conversation_views,
    audit_views,
    conversation_approval_views,
    conversation_mobile_extension_views,
    conversation_mobile_retry_views,
    conversation_mobile_views,
    conversation_thread_views,
    conversational_views,
    dashboard_dispatch_views,
    findings_views,
    governance_workspace_views,
    intelligence_views,
    lab_views,
    operations_views,
    public_consent_views,
    readiness,
    remediation_final_report_conversation_views,
    remediation_final_report_views,
    remediation_publication_views,
    remediation_review_conversation_views,
    remediation_review_views,
    remediation_views,
    report_views,
    retest_conversation_views,
    retest_views,
    source_hunt_views,
    stream_views,
    unified_assessment_views,
    views,
)

urlpatterns = [
    path("health/", views.health_view, name="web-health"),
    path("ready/", readiness.deployment_readiness_view, name="web-deployment-readiness"),
    path("login/", unified_assessment_views.UnifiedLoginView.as_view(), name="web-login"),
    path("logout/", views.logout_view, name="web-logout"),
    path("", dashboard_dispatch_views.dashboard_view, name="web-dashboard"),
    path(
        "workspace/message/",
        conversational_views.message_view,
        name="web-conversation-message",
    ),
    path(
        "workspace/public-consent/verify/",
        public_consent_views.verify_public_consent_view,
        name="web-public-consent-verify",
    ),
    path(
        "workspace/active-validation/",
        active_validation_conversation_views.active_validation_chat_view,
        name="web-conversation-active-validation",
    ),
    path(
        "workspace/remediation/",
        remediation_views.remediation_chat_view,
        name="web-conversation-remediation",
    ),
    path(
        "workspace/remediation-review/",
        remediation_review_conversation_views.remediation_review_chat_view,
        name="web-conversation-remediation-review",
    ),
    path(
        "workspace/remediation-final-report/",
        remediation_final_report_conversation_views.remediation_final_report_chat_view,
        name="web-conversation-remediation-final-report",
    ),
    path(
        "workspace/retest/",
        retest_conversation_views.retest_chat_view,
        name="web-conversation-retest",
    ),
    path(
        "workspace/threads/",
        conversation_thread_views.thread_list_view,
        name="web-conversation-thread-list",
    ),
    path(
        "workspace/reasoning/",
        conversation_thread_views.thread_reasoning_view,
        name="web-conversation-reasoning",
    ),
    path(
        "workspace/threads/new/",
        conversation_thread_views.thread_create_view,
        name="web-conversation-thread-create",
    ),
    path(
        "workspace/threads/<str:thread_id>/rename/",
        conversation_thread_views.thread_rename_view,
        name="web-conversation-thread-rename",
    ),
    path(
        "workspace/threads/<str:thread_id>/archive/",
        conversation_thread_views.thread_archive_view,
        name="web-conversation-thread-archive",
    ),
    path(
        "workspace/attachments/",
        conversation_mobile_views.attachment_view,
        name="web-conversation-attachment",
    ),
    path(
        "workspace/uploads/start/",
        conversation_mobile_views.upload_start_view,
        name="web-conversation-upload-start",
    ),
    path(
        "workspace/uploads/<str:upload_id>/chunk/",
        conversation_mobile_views.upload_chunk_view,
        name="web-conversation-upload-chunk",
    ),
    path(
        "workspace/uploads/<str:upload_id>/status/",
        conversation_mobile_views.upload_status_view,
        name="web-conversation-upload-status",
    ),
    path(
        "workspace/uploads/<str:upload_id>/cancel/",
        conversation_mobile_views.upload_cancel_view,
        name="web-conversation-upload-cancel",
    ),
    path(
        "workspace/mobile-message/",
        conversation_mobile_views.mobile_message_view,
        name="web-conversation-mobile-message",
    ),
    path(
        "workspace/mobile-followup/",
        conversation_mobile_views.mobile_followup_view,
        name="web-conversation-mobile-followup",
    ),
    path(
        "workspace/mobile-context/",
        conversation_mobile_views.mobile_context_view,
        name="web-conversation-mobile-context",
    ),
    path(
        "workspace/mobile-context/reset/",
        conversation_mobile_views.mobile_context_reset_view,
        name="web-conversation-mobile-context-reset",
    ),
    path(
        "workspace/mobile-retry/",
        conversation_mobile_retry_views.mobile_retry_view,
        name="web-conversation-mobile-retry",
    ),
    path(
        "workspace/mobile-runs/<str:job_id>/status/",
        conversation_mobile_views.mobile_status_view,
        name="web-conversation-mobile-status",
    ),
    path(
        "workspace/mobile-activity/<str:run_id>/stream/",
        conversation_mobile_views.mobile_activity_stream_view,
        name="web-conversation-mobile-activity-stream",
    ),
    path(
        "workspace/mobile-extensions/approve/",
        conversation_mobile_extension_views.mobile_extension_approve_view,
        name="web-conversation-mobile-extension-approve",
    ),
    path(
        "workspace/mobile-extensions/<str:job_id>/status/",
        conversation_mobile_extension_views.mobile_extension_status_view,
        name="web-conversation-mobile-extension-status",
    ),
    path(
        "workspace/approve/",
        conversation_approval_views.approve_view,
        name="web-conversation-approve",
    ),
    path(
        "workspace/reset/",
        conversational_views.reset_view,
        name="web-conversation-reset",
    ),
    path(
        "workspace/runs/<str:run_id>/status/",
        conversational_views.status_view,
        name="web-conversation-status",
    ),
    path(
        "workspace/runs/<str:run_id>/activity/stream/",
        conversational_views.activity_stream_view,
        name="web-conversation-activity-stream",
    ),
    path("source-hunt/", source_hunt_views.source_hunt_view, name="web-source-hunt"),
    path("status/", views.status_view, name="web-status"),
    path("audit/", audit_views.audit_overview_view, name="web-audit-overview"),
    path("authorizations/", views.authorization_list_view, name="web-authorization-list"),
    path(
        "authorizations/<str:authorization_id>/",
        views.authorization_detail_view,
        name="web-authorization-detail",
    ),
    path(
        "authorizations/<str:authorization_id>/revoke/",
        views.authorization_revoke_view,
        name="web-authorization-revoke",
    ),
    path(
        "scans/new/",
        RedirectView.as_view(url="/?intent=new-assessment", permanent=False),
        name="web-new-scan",
    ),
    path("scans/", unified_assessment_views.assessment_list_view, name="web-scan-run-list"),
    path(
        "scans/<str:run_id>/",
        unified_assessment_views.assessment_detail_view,
        name="web-scan-run-detail",
    ),
    path(
        "scans/<str:run_id>/activity/",
        unified_assessment_views.assessment_activity_view,
        name="web-agent-run-activity",
    ),
    path(
        "scans/<str:run_id>/activity/stream/",
        unified_assessment_views.assessment_activity_stream_view,
        name="web-agent-run-activity-stream",
    ),
    path(
        "scans/<str:assessment_id>/active-validation/new/",
        lab_views.lab_create_view,
        name="web-lab-create",
    ),
    path(
        "active-validation/<str:lab_id>/",
        lab_views.lab_detail_view,
        name="web-lab-detail",
    ),
    path(
        "active-validation/<str:lab_id>/approve/",
        lab_views.lab_approve_view,
        name="web-lab-approve",
    ),
    path(
        "active-validation/<str:lab_id>/queue/",
        lab_views.lab_queue_view,
        name="web-lab-queue",
    ),
    path(
        "active-validation/<str:lab_id>/stop/",
        lab_views.lab_stop_view,
        name="web-lab-stop",
    ),
    path(
        "active-validation/<str:lab_id>/activity/stream/",
        lab_views.lab_activity_stream_view,
        name="web-lab-activity-stream",
    ),
    path("reviews/", views.review_queue_view, name="web-review-queue"),
    path(
        "reviews/<str:assignment_reference>/",
        governance_workspace_views.review_workspace_view,
        name="web-review-detail",
    ),
    path("adjudications/", views.adjudication_queue_view, name="web-adjudication-queue"),
    path(
        "adjudications/<str:assignment_reference>/",
        governance_workspace_views.adjudication_workspace_view,
        name="web-adjudication-detail",
    ),
    path("releases/", views.release_list_view, name="web-release-list"),
    path(
        "releases/<str:campaign_id>/",
        governance_workspace_views.release_detail_view,
        name="web-release-detail",
    ),
    path("datasets/", views.dataset_list_view, name="web-dataset-list"),
    path(
        "datasets/<str:campaign_id>/",
        governance_workspace_views.dataset_detail_view,
        name="web-dataset-detail",
    ),
    path("models/", intelligence_views.model_list_view, name="web-model-list"),
    path(
        "models/<slug:component_id>/",
        intelligence_views.model_detail_view,
        name="web-model-detail",
    ),
    path("findings/", findings_views.findings_overview_view, name="web-findings-overview"),
    path(
        "findings/<str:finding_id>/remediation/new/",
        remediation_views.remediation_create_view,
        name="web-remediation-create",
    ),
    path(
        "findings/<str:finding_id>/remediation/",
        remediation_views.remediation_detail_view,
        name="web-remediation-detail",
    ),
    path(
        "findings/<str:finding_id>/remediation/verify/",
        remediation_views.remediation_verify_view,
        name="web-remediation-verify",
    ),
    path(
        "findings/<str:finding_id>/remediation/review/",
        remediation_review_views.remediation_review_view,
        name="web-remediation-review",
    ),
    path(
        "findings/<str:finding_id>/remediation/report/",
        remediation_final_report_views.remediation_final_report_view,
        name="web-remediation-final-report",
    ),
    path(
        "findings/<str:finding_id>/remediation/report/publication/",
        remediation_publication_views.remediation_publication_view,
        name="web-remediation-publication",
    ),
    path(
        "findings/<str:finding_id>/remediation/report/download/<slug:artifact_format>/",
        remediation_final_report_views.remediation_final_report_download_view,
        name="web-remediation-final-report-download",
    ),
    path(
        "findings/<str:finding_id>/remediation/cancel/",
        remediation_views.remediation_cancel_view,
        name="web-remediation-cancel",
    ),
    path(
        "findings/<str:finding_id>/retest/new/",
        retest_views.retest_create_view,
        name="web-retest-create",
    ),
    path(
        "findings/<str:finding_id>/retest/",
        retest_views.retest_detail_view,
        name="web-retest-detail",
    ),
    path(
        "findings/<str:finding_id>/retest/cancel/",
        retest_views.retest_cancel_view,
        name="web-retest-cancel",
    ),
    path(
        "findings/<str:finding_id>/",
        governance_workspace_views.finding_detail_view,
        name="web-finding-detail",
    ),
    path(
        "machine-oracle/",
        RedirectView.as_view(pattern_name="web-scan-run-list", permanent=False),
        name="web-oracle-overview",
    ),
    path("reports/", report_views.reports_overview_view, name="web-reports-overview"),
    path(
        "reports/plans/<str:plan_id>/download/<slug:export_format>/",
        report_views.pilot_plan_download_view,
        name="web-pilot-plan-download",
    ),
    path("governance/", views.governance_overview_view, name="web-governance-overview"),
    path("settings/", views.settings_overview_view, name="web-settings-overview"),
    path("campaigns/", views.campaign_list_view, name="web-campaign-list"),
    path("campaigns/<str:campaign_id>/", views.campaign_detail_view, name="web-campaign-detail"),
    path("readiness/<str:campaign_id>/", views.readiness_view, name="web-readiness-detail"),
    path("roles/", views.role_list_view, name="web-role-list"),
    path("roles/<str:role_id>/", views.role_detail_view, name="web-role-detail"),
    path("skills/", views.skill_list_view, name="web-skill-list"),
    path("skills/<str:skill_id>/", views.skill_detail_view, name="web-skill-detail"),
    path("agent/runs/", views.agent_run_list_view, name="web-agent-run-list"),
    path(
        "agent/runs/<str:run_id>/",
        unified_assessment_views.assessment_detail_view,
        name="web-agent-run-detail",
    ),
    path(
        "agent/runs/<str:run_id>/legacy/",
        RedirectView.as_view(pattern_name="web-scan-run-detail", permanent=False),
        name="legacy-run-detail",
    ),
    path(
        "agent/runs/<str:run_id>/activity/",
        views.agent_activity_view,
        name="web-legacy-agent-run-activity",
    ),
    path(
        "agent/runs/<str:run_id>/activity/stream/",
        stream_views.agent_activity_stream_view,
        name="web-legacy-agent-run-activity-stream",
    ),
    path("agent/runs/<str:run_id>/stop/", views.stop_run_view, name="web-agent-run-stop"),
    path("approvals/", operations_views.approval_list_view, name="web-approval-list"),
    path(
        "approvals/<str:request_id>/",
        operations_views.approval_detail_view,
        name="web-approval-detail",
    ),
    path(
        "approvals/<str:request_id>/decision/",
        operations_views.approval_decision_view,
        name="web-approval-decision",
    ),
    path(
        "security-tools/",
        operations_views.security_tool_registry_view,
        name="web-security-tool-registry",
    ),
    path(
        "advanced-assessment/",
        operations_views.advanced_profiles_view,
        name="web-advanced-profiles",
    ),
    path(
        "mobile-analysis/",
        dashboard_dispatch_views.dashboard_view,
        name="web-mobile-analysis",
    ),
    path("pilot/plans/", views.pilot_plan_list_view, name="web-pilot-plan-list"),
    path("pilot/plans/<str:plan_id>/", views.pilot_plan_detail_view, name="web-pilot-plan-detail"),
    path(
        "pilot/plans/<str:plan_id>/validation/",
        views.pilot_plan_validation_view,
        name="web-pilot-plan-validation",
    ),
]
