"""Safe, deterministic downloadable report and evidence artifacts."""

from __future__ import annotations

import hashlib
import html
import json
import re
import zipfile
from collections.abc import Iterable
from pathlib import Path

from vulnhunter.reports.models import DownloadArtifact, DownloadFormat
from vulnhunter.reports.service import _reject_protected_payload
from vulnhunter.security import redact_text

_SAFE_NAME = re.compile(r"[^a-zA-Z0-9._-]+")


class ReportExportError(RuntimeError):
    pass


class ReportExporter:
    def __init__(self, output_root: Path, *, maximum_artifact_bytes: int = 100_000_000) -> None:
        self.output_root = output_root.expanduser().resolve()
        self.output_root.mkdir(parents=True, exist_ok=True)
        self.maximum_artifact_bytes = maximum_artifact_bytes

    def export_json(
        self,
        *,
        artifact_id: str,
        payload: dict[str, object],
        provenance: tuple[str, ...],
    ) -> DownloadArtifact:
        self._validate_payload(payload)
        data = (
            json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False).encode("utf-8")
            + b"\n"
        )
        return self._write(artifact_id, DownloadFormat.JSON, "application/json", data, provenance)

    def export_html(
        self,
        *,
        artifact_id: str,
        title: str,
        payload: dict[str, object],
        provenance: tuple[str, ...],
    ) -> DownloadArtifact:
        self._validate_payload(payload)
        body = self._render_value(payload)
        document = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title>
<style>
body {{
  font-family: system-ui;
  margin: 2rem;
  max-width: 1100px;
  background: #081318;
  color: #e8f5f2;
}}
h1, h2 {{ color: #73e7c4; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{
  border: 1px solid #284247;
  padding: .6rem;
  text-align: left;
  vertical-align: top;
}}
code, pre {{
  white-space: pre-wrap;
  background: #10242a;
  padding: .3rem;
  border-radius: .3rem;
}}
.meta {{ color: #9bb6b2; }}
</style>
</head>
<body>
<h1>{html.escape(title)}</h1>
<p class="meta">
Generated by VulnHunter AI. Verified facts, observations, analyst decisions and
unresolved conflicts must remain distinct.
</p>
{body}
</body>
</html>"""
        return self._write(
            artifact_id,
            DownloadFormat.HTML,
            "text/html; charset=utf-8",
            document.encode(),
            provenance,
        )

    def export_sarif(
        self,
        *,
        artifact_id: str,
        findings: Iterable[dict[str, object]],
        provenance: tuple[str, ...],
    ) -> DownloadArtifact:
        results = []
        rules: dict[str, dict[str, object]] = {}
        for finding in findings:
            self._validate_payload(finding)
            rule_id = str(finding.get("cwe") or finding.get("rule_id") or "vulnhunter-observation")
            rules.setdefault(
                rule_id, {"id": rule_id, "name": str(finding.get("title", rule_id))[:200]}
            )
            results.append(
                {
                    "ruleId": rule_id,
                    "level": self._sarif_level(str(finding.get("severity", "warning"))),
                    "message": {
                        "text": str(finding.get("description", finding.get("title", "Finding")))[
                            :10_000
                        ]
                    },
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {"uri": str(finding.get("path", "unknown"))},
                                "region": {"startLine": max(1, int(finding.get("line", 1)))},
                            }
                        }
                    ],
                    "properties": {
                        "verification": str(finding.get("verification", "observed")),
                        "confidence": finding.get("confidence"),
                    },
                }
            )
        payload = {
            "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
            "version": "2.1.0",
            "runs": [
                {
                    "tool": {"driver": {"name": "VulnHunter AI", "rules": list(rules.values())}},
                    "results": results,
                }
            ],
        }
        return self._write(
            artifact_id,
            DownloadFormat.SARIF,
            "application/sarif+json",
            (json.dumps(payload, sort_keys=True, indent=2) + "\n").encode(),
            provenance,
        )

    def export_evidence_zip(
        self,
        *,
        artifact_id: str,
        evidence_files: tuple[Path, ...],
        manifest: dict[str, object],
        provenance: tuple[str, ...],
        approved_roots: tuple[Path, ...],
    ) -> DownloadArtifact:
        self._validate_payload(manifest)
        approved = tuple(root.expanduser().resolve(strict=True) for root in approved_roots)
        path = self._destination(artifact_id, DownloadFormat.EVIDENCE_ZIP)
        temporary = path.with_suffix(path.suffix + ".tmp")
        temporary.unlink(missing_ok=True)
        entries: list[dict[str, object]] = []
        try:
            with zipfile.ZipFile(
                temporary,
                "w",
                compression=zipfile.ZIP_DEFLATED,
            ) as archive:
                for index, source in enumerate(evidence_files):
                    expanded = source.expanduser()
                    if expanded.is_symlink():
                        raise ReportExportError("evidence file is outside approved roots")
                    resolved = expanded.resolve(strict=True)
                    if not any(self._within(resolved, root) for root in approved):
                        raise ReportExportError("evidence file is outside approved roots")
                    raw = resolved.read_bytes()
                    if len(raw) > self.maximum_artifact_bytes:
                        raise ReportExportError("individual evidence file exceeds size limit")
                    safe = self._safe_filename(resolved.name)
                    self._reject_protected_evidence(raw, filename=safe)
                    archive_name = f"evidence/{index:04d}-{safe}"
                    archive.writestr(archive_name, raw)
                    entries.append(
                        {
                            "name": archive_name,
                            "sha256": hashlib.sha256(raw).hexdigest(),
                            "size_bytes": len(raw),
                        }
                    )
                archive.writestr(
                    "manifest.json",
                    json.dumps(
                        {"metadata": manifest, "entries": entries},
                        sort_keys=True,
                        indent=2,
                    )
                    + "\n",
                )
            temporary.replace(path)
        except Exception:
            temporary.unlink(missing_ok=True)
            raise
        return self._finalize_existing(
            artifact_id, DownloadFormat.EVIDENCE_ZIP, "application/zip", path, provenance
        )

    def export_attack_path_svg(
        self,
        *,
        artifact_id: str,
        nodes: tuple[str, ...],
        provenance: tuple[str, ...],
    ) -> DownloadArtifact:
        if not nodes:
            raise ReportExportError("attack path requires at least one node")
        width = max(640, len(nodes) * 220)
        parts = [
            (
                '<svg xmlns="http://www.w3.org/2000/svg" '
                f'width="{width}" height="180" viewBox="0 0 {width} 180">'
            ),
            '<rect width="100%" height="100%" fill="#081318"/>',
        ]
        for index, label in enumerate(nodes):
            x = 30 + index * 210
            parts.append(
                f'<rect x="{x}" y="60" width="170" height="58" rx="12" '
                'fill="#102a30" stroke="#55d8b1"/>'
            )
            parts.append(
                f'<text x="{x + 85}" y="94" fill="#e8f5f2" '
                'text-anchor="middle" font-family="system-ui" font-size="13">'
                f"{html.escape(label[:30])}</text>"
            )
            if index < len(nodes) - 1:
                parts.append(
                    f'<path d="M{x + 170} 89 H{x + 205}" stroke="#e8b949" '
                    'stroke-width="3" marker-end="url(#a)"/>'
                )
        parts.insert(
            2,
            (
                '<defs><marker id="a" viewBox="0 0 10 10" refX="8" refY="5" '
                'markerWidth="6" markerHeight="6" orient="auto">'
                '<path d="M0 0 L10 5 L0 10z" fill="#e8b949"/>'
                "</marker></defs>"
            ),
        )
        parts.append("</svg>")
        return self._write(
            artifact_id,
            DownloadFormat.ATTACK_PATH_SVG,
            "image/svg+xml",
            "".join(parts).encode(),
            provenance,
        )

    def _validate_payload(self, payload: dict[str, object]) -> None:
        _reject_protected_payload(payload, seen=set())

    @staticmethod
    def _reject_protected_evidence(raw: bytes, *, filename: str) -> None:
        text = raw.decode("utf-8", errors="replace")
        if redact_text(text) != text:
            raise ReportExportError(
                f"evidence file contains protected data and cannot be exported: {filename}"
            )

    def _write(self, artifact_id, format, content_type, data, provenance):
        if len(data) > self.maximum_artifact_bytes:
            raise ReportExportError("artifact exceeds size limit")
        path = self._destination(artifact_id, format)
        temporary = path.with_suffix(path.suffix + ".tmp")
        temporary.write_bytes(data)
        temporary.replace(path)
        return self._finalize_existing(artifact_id, format, content_type, path, provenance)

    def _finalize_existing(self, artifact_id, format, content_type, path, provenance):
        size = path.stat().st_size
        if size > self.maximum_artifact_bytes:
            path.unlink(missing_ok=True)
            raise ReportExportError("artifact exceeds size limit")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        return DownloadArtifact(
            artifact_id=artifact_id,
            format=format,
            filename=path.name,
            content_type=content_type,
            path=str(path),
            sha256=digest,
            size_bytes=size,
            provenance=provenance,
        )

    def _destination(self, artifact_id, format):
        safe = self._safe_filename(artifact_id)
        extensions = {
            DownloadFormat.JSON: ".json",
            DownloadFormat.HTML: ".html",
            DownloadFormat.SARIF: ".sarif.json",
            DownloadFormat.EVIDENCE_ZIP: ".zip",
            DownloadFormat.ATTACK_PATH_SVG: ".svg",
        }
        destination = (self.output_root / f"{safe}{extensions[format]}").resolve()
        if not self._within(destination, self.output_root) or destination.is_symlink():
            raise ReportExportError("unsafe artifact destination")
        return destination

    @staticmethod
    def _safe_filename(value: str) -> str:
        safe = _SAFE_NAME.sub("-", value).strip(".-")
        if not safe or len(safe) > 180:
            raise ReportExportError("unsafe artifact filename")
        return safe

    @staticmethod
    def _within(path: Path, root: Path) -> bool:
        try:
            path.relative_to(root)
        except ValueError:
            return False
        return True

    @staticmethod
    def _sarif_level(severity: str) -> str:
        return {
            "critical": "error",
            "high": "error",
            "medium": "warning",
            "low": "note",
            "info": "note",
        }.get(severity.lower(), "warning")

    def _render_value(self, value: object) -> str:
        if isinstance(value, dict):
            rows = "".join(
                f"<tr><th>{html.escape(str(key))}</th><td>{self._render_value(item)}</td></tr>"
                for key, item in value.items()
            )
            return f"<table>{rows}</table>"
        if isinstance(value, (list, tuple)):
            return (
                "<ol>" + "".join(f"<li>{self._render_value(item)}</li>" for item in value) + "</ol>"
            )
        return f"<code>{html.escape(str(value))}</code>"
