"""Reviewed-dataset and leakage-resistant local ML pipeline."""

from vulnhunter.ml.dataset import (
    build_dataset,
    dataset_sha256,
    export_jsonl,
    to_model_input,
)
from vulnhunter.ml.diagnostics import (
    DiagnosticCase,
    DiagnosticReport,
    DiagnosticSlice,
    diagnose_holdout,
)
from vulnhunter.ml.features import build_feature_schema, vectorize
from vulnhunter.ml.models import (
    BenchmarkProvenance,
    EvaluationMetrics,
    FeatureSchema,
    ModelArtifact,
    ModelType,
    ObservationInput,
    Prediction,
    TrainingExample,
    TrainingLabel,
    TuningSummary,
)
from vulnhunter.ml.quality import (
    DatasetQualityReport,
    PreparedTrainingDataset,
    assess_dataset_quality,
)
from vulnhunter.ml.release_training import (
    GovernedModelCandidate,
    ProductionTrainingPackage,
    ReleaseTrainingBoundaryError,
    TrainingPackageApplication,
    TrainingPackageExample,
    TrainingPackageExclusion,
    TrainingReleaseEvent,
    TrainingReleaseLedger,
    build_production_training_package,
    governed_model_candidate_sha256,
    production_training_package_sha256,
    register_training_release,
    train_production_baseline,
    train_production_tuned,
    training_release_event_sha256,
    transition_training_release,
)
from vulnhunter.ml.splitting import split_by_scan_groups
from vulnhunter.ml.training import (
    load_model,
    predict,
    save_model,
    train_baseline,
    train_tuned,
)
from vulnhunter.ml.tuning import (
    GroupFold,
    TuningResult,
    build_two_fold_group_cv,
    tune_model,
)

__all__ = [
    "BenchmarkProvenance",
    "DatasetQualityReport",
    "DiagnosticCase",
    "DiagnosticReport",
    "DiagnosticSlice",
    "EvaluationMetrics",
    "FeatureSchema",
    "GovernedModelCandidate",
    "GroupFold",
    "ModelArtifact",
    "ModelType",
    "ObservationInput",
    "Prediction",
    "PreparedTrainingDataset",
    "ProductionTrainingPackage",
    "ReleaseTrainingBoundaryError",
    "TrainingExample",
    "TrainingLabel",
    "TrainingPackageApplication",
    "TrainingPackageExample",
    "TrainingPackageExclusion",
    "TrainingReleaseEvent",
    "TrainingReleaseLedger",
    "TuningResult",
    "TuningSummary",
    "assess_dataset_quality",
    "build_dataset",
    "build_feature_schema",
    "build_production_training_package",
    "build_two_fold_group_cv",
    "dataset_sha256",
    "diagnose_holdout",
    "export_jsonl",
    "governed_model_candidate_sha256",
    "load_model",
    "predict",
    "production_training_package_sha256",
    "register_training_release",
    "save_model",
    "split_by_scan_groups",
    "to_model_input",
    "train_baseline",
    "train_production_baseline",
    "train_production_tuned",
    "train_tuned",
    "training_release_event_sha256",
    "transition_training_release",
    "tune_model",
    "vectorize",
]
